# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "code-app"
client_id = "aae6a8acb4b183df7af81d34cef21e46"
application_url = "https://address-vice-availability-measurements.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://address-vice-availability-measurements.trycloudflare.com/auth/callback",
  "https://address-vice-availability-measurements.trycloudflare.com/auth/shopify/callback",
  "https://address-vice-availability-measurements.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "test-pod-app.myshopify.com"
